#!/bin/sh
#
# ~/.xinitrc
# Executed by startx (run your window manager from here)

xset r rate 200 60
xrandr --output HDMI-1 --auto --right-of DP-2
xsetroot -cursor_name left_ptr &
dunst&
xscreensaver&
exec stack exec xmonad
